#!/usr/bin/env bash
# Phase 0: Configure Helm repo-shims for Seiji chart dependency resolution
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
REPOS_DIR="$PROJECT_ROOT/repos"
SHIMS_DIR="$PROJECT_ROOT/configs/repo-shims"

echo "=== Phase 0: Repo-Shims Setup ==="

# Load access env if present
ACCESS_ENV="$PROJECT_ROOT/configs/access/access.env"
if [ -f "$ACCESS_ENV" ]; then
  # shellcheck source=/dev/null
  source "$ACCESS_ENV"
fi

export REPO_SHIMS_DIR="${REPO_SHIMS_DIR:-$SHIMS_DIR}"
mkdir -p "$REPO_SHIMS_DIR/.cache"

# Local file:// shims from cloned repos (Kitchen Sous Chef pattern)
register_local_shim() {
  local name="$1"
  local path="$2"
  if [ -d "$path" ]; then
    helm repo add "$name" "file://$path" 2>/dev/null || helm repo add "$name" "file://$path" --force-update 2>/dev/null || true
    echo "  [OK]   $name -> file://$path"
  else
    echo "  [SKIP] $name — $path not found (clone repos first)"
  fi
}

if command -v helm &>/dev/null; then
  echo ""
  echo "Registering local Helm shims:"
  register_local_shim "kitchen-sous-chef" "$REPOS_DIR/kitchen-sous-chef/charts"
  register_local_shim "onyx-helmsman" "$REPOS_DIR/onyx-helmsman/charts"
  register_local_shim "firely-charts" "$REPOS_DIR/firely-fsi-image/helm"

  # S3-backed chart museum (production)
  if [ -n "${HELM_CHARTS_BUCKET:-}" ] && command -v aws &>/dev/null; then
    if aws s3 ls "${HELM_CHARTS_BUCKET%/}/" &>/dev/null; then
      helm repo add onyx-charts "${HELM_CHARTS_BUCKET%/}/" 2>/dev/null \
        || helm repo add onyx-charts "${HELM_CHARTS_BUCKET%/}/" --force-update 2>/dev/null || true
      echo "  [OK]   onyx-charts -> ${HELM_CHARTS_BUCKET%/}/"
    else
      echo "  [SKIP] onyx-charts S3 bucket unreachable (expected without AWS access)"
    fi
  fi

  helm repo update 2>/dev/null || true
  echo ""
  echo "Registered Helm repos:"
  helm repo list 2>/dev/null || echo "  (none)"
else
  echo "  [WARN] helm not installed — install for Seiji deploys"
fi

# Write resolved shim index for Seiji
cat > "$REPO_SHIMS_DIR/.shim-index" <<EOF
# Generated by setup_repo_shims.sh — do not edit
generated_at=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
repos_dir=$REPOS_DIR
helm_charts_bucket=${HELM_CHARTS_BUCKET:-unset}
EOF

echo ""
echo "Repo-shims index: $REPO_SHIMS_DIR/.shim-index"
