#!/usr/bin/env bash
# Phase 0: Trace 5-stage Cambia Facets Claims architecture
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

echo "=== Cambia Facets Claims — 5-Stage Architecture Trace ==="
echo ""
echo "Stage 1 — Source & Network"
echo "  Source:  Cambia on-prem Facets SQL Server 2016 (CDC read replica)"
echo "  Network: Site-to-site VPN (Palo Alto) → cambia-facets-networking (697410135799)"
echo "  Repos:   facets-core, facets-infrastructure"
echo ""
echo "Stage 2 — CDC Extraction"
echo "  Orchestration: Step Functions + Lambda + AWS Batch"
echo "  Output:  ~25 encrypted JSON files + manifest.json"
echo "  S3:      abacus-facets-intermediate-<env>/claims-incremental/"
echo "  Lock:    DynamoDB CdcGlobals (one job per domain)"
echo ""
echo "Stage 3 — Landing & Bronze"
echo "  Path:    SFTP landing → NextGen raw S3 (cambia02)"
echo "  Load:    Databricks bronze SCD2 (44+ tables, AIR library)"
echo "  Key:     CMC_CLCL_CLAIM, CMC_CDML_CL_LINE, CMC_CDDL_CL_LINE"
echo ""
echo "Stage 4 — Silver & Gold"
echo "  Silver:  silver.unified_timeline_claim, silver.claim_facets*"
echo "  Gold:    gold.fm_claim (Interop) ║ gold.fm_claim_cambia (CDP)"
echo ""
echo "Stage 5 — Downstream"
echo "  SAM/FHIR: ng-pipelines-onyx → cambia02-claims-dataingestion-workflow"
echo "  Snowflake: bronze → silver → gold (XFORM-3515)"
echo "  MDM:       Silver → Reltio tenant"
echo ""
echo "Triggers: ~4 hr schedule + Facets_BatchJobComplete_* nightly file"
echo "Volumes:  ~99M claims historical; 70k–120k nightly batch"
echo ""
echo "PASS: Architecture trace complete"
